import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-expect-error: side-effect import for bootstrap CSS
import 'bootstrap/dist/css/bootstrap.min.css';
// @ts-expect-error: side-effect import for global CSS
import "./globals.css";
import Footer from '@/components/Footer';
import NavBar from '@/components/Navbar';
import Providers from './providers';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digits",
  description: "Generated by ics-software-engineering.github.io",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classString = `${geistSans.variable} ${geistMono.variable} wrapper`;
  return (
    <html lang="en">
      <body className={classString}>
       <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}